# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c7518805c8780712fc4f99b3a4532272463ebf28e56d07273d3101233f54f8e708f8b179f4f14d65ab177c1f2ab546e8b0567c47b52dbdef02828310dd20d8

test:
  secret_key_base: 3feec435182e55d173a9497b1fdfc7adb5ab8d02fb696c933d9943091643c61be10dd7d6d043fd65b022e08ab18be868347f45633fa51d1627bd9c76e91f0c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
